# fly.toml (mira-python-plot)
from flask import Flask, request, jsonify

app = "mira-python-plot"      # o el nombre que te sugiera Fly
primary_region = "scl"        # "scl" (Santiago) o el que prefieras

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "10s"
  restart_limit = 0

[[services.http_checks]]
  interval = "15s"
  timeout = "5s"
  grace_period = "10s"
  method = "get"
  path = "/healthz"
  protocol = "http"

@app.get("/healthz")
def healthz():
    return jsonify({"ok": True}), 200
